ARG BASE_IMAGE
FROM $BASE_IMAGE

LABEL maintainer="Marco Capuccini <marco.capuccini@it.uu.se>" \
      ambari.role="server"

RUN apt-get -y update && \
    mkdir -p /usr/share/man/man1 && \
    mkdir -p /usr/share/man/man7 && \
    apt-get -y install ambari-server && \
    apt-get -y autoremove && \
    apt-get clean && \
    ambari-server setup --silent
